In [11]:
import torch as t
import einops

In [15]:
n, m, p = 4, 5, 6

A = t.arange(1, n*m+1).reshape((n,m))
B = A + 1

t.einsum('... , ... -> ...', A, B)

tensor([[  2,   6,  12,  20,  30],
        [ 42,  56,  72,  90, 110],
        [132, 156, 182, 210, 240],
        [272, 306, 342, 380, 420]])

In [17]:
A * B

tensor([[  2,   6,  12,  20,  30],
        [ 42,  56,  72,  90, 110],
        [132, 156, 182, 210, 240],
        [272, 306, 342, 380, 420]])

In [19]:
u = t.randint(-10, 10, (5,))
v = t.randint(-10, 10, (3,))
u, v

(tensor([ -9, -10,  -5,   4,  -3]), tensor([ 1, -8,  0]))

In [23]:
t.einsum('i,j->ij', u, v)

tensor([[ -9,  72,   0],
        [-10,  80,   0],
        [ -5,  40,   0],
        [  4, -32,   0],
        [ -3,  24,   0]])

In [26]:
A
b = t.arange(1, 6)
A, b

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]),
 tensor([1, 2, 3, 4, 5]))

In [27]:
t.einsum('ij,j->ij', A, b)

tensor([[  1,   4,   9,  16,  25],
        [  6,  14,  24,  36,  50],
        [ 11,  24,  39,  56,  75],
        [ 16,  34,  54,  76, 100]])

In [30]:
A = t.tensor([[1, 2],[3,4]])
delta = t.tensor([[[1,0],[0,0]],[[0,0],[0,1]]])

A, delta

(tensor([[1, 2],
         [3, 4]]),
 tensor([[[1, 0],
          [0, 0]],
 
         [[0, 0],
          [0, 1]]]))

In [31]:
t.einsum('ij,jkl->ikl', A, delta)

tensor([[[1, 0],
         [0, 2]],

        [[3, 0],
         [0, 4]]])