In [4]:
%load_ext autoreload
%autoreload 2
import gpt_model
import data
import torch as t

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [126]:
n_lin_layers, n_parts = 4, 5
layers = ['Linear', 'ReLU'] * (n_lin_layers-1) + ['Linear']

starts = 2*t.linspace(0, n_lin_layers, n_parts + 1).int()[:-1]
ends = 2*t.linspace(0, n_lin_layers, n_parts + 1).int()[1:]

models = [layers[s:e] for s, e in zip(starts, ends)]
models

[[], ['Linear', 'ReLU'], ['Linear', 'ReLU'], ['Linear', 'ReLU'], ['Linear']]

In [133]:
shape_holder = -t.ones((8,), dtype=t.int32)
shape = t.tensor((1, 2, 3))

In [134]:
shape_holder

tensor([-1, -1, -1, -1, -1, -1, -1, -1], dtype=torch.int32)

In [137]:
shape_holder[-len(shape):] = shape
shape_holder = shape_holder.clone()

In [138]:
shape_holder[shape_holder != -1].tolist()

[1, 2, 3]

In [128]:
t.arange(5,15).dtype

torch.int64

In [120]:
starts

tensor([0, 1, 2, 3], dtype=torch.int32)

In [111]:
list(range(0, 100, 5))

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [79]:
train, test = data.get_data(fake=True)

imdb


In [91]:
train, test= data.identity_data(32, 16, 10)

In [104]:
x = t.tensor(10)

In [108]:
x == 10

tensor(True)

In [99]:
test[0][0].shape

torch.Size([32, 16])

In [100]:
test[0][1].shape

torch.Size([32, 16])

In [103]:
test[0][2]

tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       dtype=torch.int32)

In [82]:
t.randint(-256, 256, (10,5))

tensor([[ -64, -189,  -35,  236, -203],
        [ 175,  -28, -241,  -83,  105],
        [  25,   51, -143, -167, -118],
        [ 175,  173,  114,  -66,  -64],
        [  18,  -12,  144,  154,  152],
        [ -60,  234,  109, -190,  182],
        [ 119,   40,  223,   25,    2],
        [ -64, -247,  180,   38,   47],
        [ 184,  -75,   77, -164,   32],
        [ -42, -105, -256, -145,  226]])

In [78]:
x[0][2].shape

torch.Size([32])

In [28]:
for batch in train:
    assert len(list(zip(*batch))) == 3
    # break

In [19]:
c = [[1, 2], [3, 4], [5, 6]]
[a for b in c for a in b]

[1, 2, 3, 4, 5, 6]

In [12]:
t.tensor(sents, dtype=t.int32)

tensor([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 1], dtype=torch.int32)

In [34]:
train[0][1][1][380]

tensor(50256)

In [ ]:
model = gpt_model.transformers.AutoModelForSequenceClassification.from_pretrained("EleutherAI/gpt-neo-125M")
gpt_model.split_model_and_save(4, model)

In [ ]:
t.ones((8,), device='cpu', dtype=t.int32)

In [ ]:
x = t.tensor([-1, -1, -1, -1, -1, 1, 5, 7], dtype=t.int32)

In [ ]:
shape = x[x != -1].tolist()
shape

In [ ]:
shape = t.randn(shape).shape

In [ ]:
t.randint(1, 10, (5,)).tolist()

In [ ]:
len(shape)

In [ ]:
shape_holder = -t.ones((8,))
shape_holder[-len(shape):] = t.tensor(shape)
shape_holder

In [ ]:
n_workers = 4
[(a, b) for a in range(n_workers) if a != b]
[(a, b) for a in range(n_workers) if a != b]